services:

  marcel-caddy:
    restart: unless-stopped
    image: caddy:2.10.2-alpine
    # ports:
    #   - "80:80"
    #   - "443:443"
    depends_on:
      - marcel-backend
    volumes:
      - ./Caddyfile.prod:/etc/caddy/Caddyfile:ro
      - ./frontend/dist:/usr/share/caddy/react:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - marcel-network
      - proxy-network   # shared external network
      
  marcel-backend:
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    image: marcel-backend
    working_dir: /app
    expose: [8000]
    env_file:
      - .env
    # environment:
      # SERVER_PORT: "8000"
      # API_SERVER_URL: ${API_SERVER_URL_LOCAL}
    networks:
      - marcel-network

networks:
  marcel-network:
    driver: bridge
  proxy-network:
    external: true

volumes:
  caddy_data:
  caddy_config:
