services:

  marcel-caddy-dev:
    image: caddy:2.10.2-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - marcel-backend-dev
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - marcel-network

  marcel-frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: marcel-frontend-dev
    ports: [5173:5173]
    env_file:
      - .env
      - ./frontend/.env
    environment:
      - VITE_API_BASE_URL=${API_SERVER_URL_LOCAL}
    networks:
      - marcel-network
    volumes:
      - node_modules:/app/node_modules # to avoid overwriting node_modules
      - ./frontend:/app
      
  marcel-backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: marcel-backend-dev
    working_dir: /app
    expose: [8000]
    env_file:
      - .env
    # environment:
      # SERVER_PORT: "8000"
      # API_SERVER_URL: ${API_SERVER_URL_LOCAL}
    volumes:
      - ./backend:/app
    networks:
      - marcel-network
   
networks:
  marcel-network:
    driver: bridge

volumes:
  node_modules:
  caddy_data:
  caddy_config:
