apiVersion: apps/v1
kind: Deployment
metadata:
  name: marcel-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marcel-backend
  template:
    metadata:
      labels:
        app: marcel-backend
    spec:
      containers:
        - name: backend
          image: marcel-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: HOST
              value: "0.0.0.0"
          envFrom:
            - secretRef:
                name: marcel-env
