apiVersion: apps/v1
kind: Deployment
metadata:
  name: marcel-caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marcel-caddy
  template:
    metadata:
      labels:
        app: marcel-caddy
    spec:
      containers:
        - name: caddy
          image: caddy:2.10.2-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            # Mount the Caddyfile
            - name: caddyfile
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
            # Mount the frontend React files
            - name: frontend
              mountPath: /usr/share/caddy/react
      volumes:
        # ConfigMap for the Caddyfile
        - name: caddyfile
          configMap:
            name: marcel-caddyfile
        # ConfigMap for the frontend
        - name: frontend
          configMap:
            name: marcel-frontend
